table FactAutoAttendantDaily
	lineageTag: 0554fb5c-e368-4d55-8b41-9f45aca6b496

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a7edd39a-1c73-4d16-9540-a015581b4997
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CallCount
		dataType: int64
		formatString: 0
		lineageTag: ba3514ea-2f08-4cc2-af27-2c2c2b2ebd6d
		summarizeBy: sum
		sourceColumn: CallCount

		annotation SummarizationSetBy = Automatic

	column ResourceAccount
		dataType: string
		lineageTag: 8c0a8a7a-c212-41b2-8dfe-4520f90a3ade
		summarizeBy: none
		sourceColumn: ResourceAccount

		annotation SummarizationSetBy = Automatic

	partition FactAutoAttendantDaily = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Projects\AHRI-Call-Dashboard-Project\data\source\AutoAttendantsUsage_9-1-2026.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Last Activity Date", type datetime}, {"Total Call Count", Int64.Type}, {"Resource Account", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Last Activity Date", "Date"}, {"Total Call Count", "CallCount"}, {"Resource Account", "ResourceAccount"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}, {"CallCount", Int64.Type}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type1",{{"ResourceAccount", Text.Trim, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"ResourceAccount", Text.Clean, type text}})
				in
				    #"Cleaned Text"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

